# import = [
#     "~/.config/alacritty/themes/themes/coolnight.toml"
# ]

import = [
    "~/.config/alacritty/themes/themes/cyber_punk_neon.toml.toml"
]
[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8

blur = false



option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 22
